language: node_js

# After creating your SDK project from this template repository,
# uncomment this section to enable builds on the appropriate node versions.
node_js:
- 12
- 14
- 16

before_install:
- npm i -g npm@8
- npm --version

script:
- npm run build
- npm run test-unit-travis || travis_terminate 1
- npm run test-integration-travis || travis_terminate 1
- npm run lint
- npm run check-packages

# To enable semantic-release, uncomment this section.
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 14
    branch: master